FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["Cardcraft.Microservice.Product/Cardcraft.Microservice.Product.csproj", "Cardcraft.Microservice.Product/"]
RUN dotnet restore "Cardcraft.Microservice.Product/Cardcraft.Microservice.Product.csproj"
COPY . .
WORKDIR "/src/Cardcraft.Microservice.Product"
RUN dotnet build "Cardcraft.Microservice.Product.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Cardcraft.Microservice.Product.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Cardcraft.Microservice.Product.dll"]